package game;

/**
 * Set of Item names.
 *
 * @author Danny Cao
 */
public enum ItemSet
{

    RED_POTION, BLUE_POTION, GREEN_POTION,
    PURPLE_BOOK, GREEN_BOOK, BLUE_BOOK, BROWN_BOOK,
    YLW_BALLOON, PNK_BALLOON, RED_BALLOON, ORNG_BALLOON, PUR_BALLOON, BLU_BALLOON,
    PUR_SQUARE, RED_SQUARE, ORNG_SQUARE, YLW_SQUARE, GRN_SQUARE, BLU_SQUARE,
    WOOD;
}
